"""add license_number to agent_applications

Revision ID: 02d0fee9211f
Revises: 131677e15428
Create Date: 2026-07-23 14:04:51.627548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d0fee9211f'
down_revision: Union[str, Sequence[str], None] = '131677e15428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_applications', sa.Column('license_number', sa.String(length=100), nullable=True))
    op.alter_column('agent_profiles', 'license_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_agent_profiles_license_number'), 'agent_profiles', ['license_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_profiles_license_number'), table_name='agent_profiles')
    op.alter_column('agent_profiles', 'license_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('agent_applications', 'license_number')
    # ### end Alembic commands ###
