"""add license_number to agent_applications

Revision ID: 131677e15428
Revises: a9c0b32bacfb
Create Date: 2026-07-23 14:02:39.387992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131677e15428'
down_revision: Union[str, Sequence[str], None] = 'a9c0b32bacfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_profiles', 'license_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_index(op.f('ix_agent_profiles_license_number'), table_name='agent_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_profiles_license_number'), 'agent_profiles', ['license_number'], unique=True)
    op.alter_column('agent_profiles', 'license_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
