"""refactor customers into user profiles

Revision ID: 2684c0e11dbb
Revises: d45f52a7ee52
Create Date: 2026-07-21 18:04:10.159628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2684c0e11dbb'
down_revision: Union[str, Sequence[str], None] = 'd45f52a7ee52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.drop_constraint(op.f('customers_user_id_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.drop_constraint(op.f('customers_user_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('customers', 'full_name')
    op.drop_column('customers', 'is_active')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_user_id_fkey'), 'customers', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.create_unique_constraint(op.f('customers_user_id_key'), 'customers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
