"""add license_number to agent_applications

Revision ID: 2e2c8d313bf1
Revises: 02d0fee9211f
Create Date: 2026-07-23 14:06:04.250452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2c8d313bf1'
down_revision: Union[str, Sequence[str], None] = '02d0fee9211f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_applications', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_applications', 'phone')
    # ### end Alembic commands ###
