"""add agent profiles and applications

Revision ID: 709b0392d47f
Revises: e832bc1e8dbb
Create Date: 2026-07-22 12:40:46.503371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709b0392d47f'
down_revision: Union[str, Sequence[str], None] = 'e832bc1e8dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='agentapplicationstatus'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_applications_id'), 'agent_applications', ['id'], unique=False)
    op.create_index(op.f('ix_agent_applications_user_id'), 'agent_applications', ['user_id'], unique=True)
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_profiles_id'), 'agent_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_agent_profiles_license_number'), 'agent_profiles', ['license_number'], unique=True)
    op.create_index(op.f('ix_agent_profiles_user_id'), 'agent_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_profiles_user_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_license_number'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_id'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    op.drop_index(op.f('ix_agent_applications_user_id'), table_name='agent_applications')
    op.drop_index(op.f('ix_agent_applications_id'), table_name='agent_applications')
    op.drop_table('agent_applications')
    # ### end Alembic commands ###
