"""link properties to agent profiles

Revision ID: 92879631e140
Revises: 709b0392d47f
Create Date: 2026-07-22 14:12:17.005326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92879631e140'
down_revision: Union[str, Sequence[str], None] = '709b0392d47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('properties_agent_id_fkey'), 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'agent_profiles', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('properties_agent_id_fkey'), 'properties', 'users', ['agent_id'], ['id'])
    # ### end Alembic commands ###
