"""fix description column type

Revision ID: 984eb4044d3c
Revises: ecd1cc1b3731
Create Date: 2026-07-16 16:40:10.739161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984eb4044d3c'
down_revision: Union[str, Sequence[str], None] = 'ecd1cc1b3731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'description',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'description',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
