"""move payment_method from properties to leads

Revision ID: a9c0b32bacfb
Revises: 883786d59a92
Create Date: 2026-07-22 16:17:00.001133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9c0b32bacfb'
down_revision: Union[str, Sequence[str], None] = '883786d59a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('payment_method', sa.Enum('CASH', 'CHEQUE', name='paymentmethod'), nullable=True))
    op.drop_column('properties', 'payment_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('payment_method', postgresql.ENUM('CASH', 'CHEQUE', name='paymentmethod'), autoincrement=False, nullable=True))
    op.drop_column('leads', 'payment_method')
    # ### end Alembic commands ###
