"""add agent foreign key to properties

Revision ID: c6d3a68bcc77
Revises: 1837f0e8b4a2
Create Date: 2026-07-21 14:23:16.048490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d3a68bcc77'
down_revision: Union[str, Sequence[str], None] = '1837f0e8b4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('agent_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_properties_agent_id'), 'properties', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'properties', 'users', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_agent_id'), table_name='properties')
    op.drop_column('properties', 'agent_id')
    # ### end Alembic commands ###
